# Generated by Django 6.0.2 on 2026-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(default=0, max_length=100, verbose_name='password1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default=0, max_length=100, verbose_name='password2'),
            preserve_default=False,
        ),
    ]
