# Generated by Django 6.0.2 on 2026-02-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_password1_customuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
